name: Check doc links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          args: docs --config ./.lychee/config.toml --offline
          format: markdown

      - name: Create Issue
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue@v5
        with:
          title: Link Checker Report
          body: ${{ steps.lychee.outputs.stdout }}
          labels: "Type:Documentation"
          assignees: jeff-bruemmer
